name: Build and test

on: # rebuild any PRs and main branch changes
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3.4.1
          with:
            node-version: '14'
            cache: 'yarn'

      - run: |
          yarn install --frozen-lockfile

      - run: |
          yarn all
