name: 'test-labels'
on:
  pull_request:
    types:
      - unlabeled
      - labeled

jobs:
  test-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"